const Types = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  INCREMENT_TO_CART: 'INCREMENT_TO_CART',
  DECREASE_TO_CART: 'DECREASE_TO_CART',
  CLEAR_ALL_FROM_CART: 'CLEAR_ALL_FROM_CART',
}

export default Types
